env:
  browser: true
  es6: true
extends: ['eslint:recommended', "plugin:react/recommended", "plugin:prettier/recommended"]
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-undef:
    - error
globals: 
  module: true
  